In [17]:
import pandas as pd
import datetime

In [20]:
재무데이터_path = 'c:\\data\\numble.csv'
휴폐업데이터_path = 'c:\\data\\휴폐업 중소법인 재무보유.xlsx'
액티브데이터_path = 'c:\\data\\액티브 중소법인 재무보유.xlsx'
fin_df = pd.read_csv(재무데이터_path, encoding = 'UTF-8-sig')
fin_df.shape

(109142, 48)

In [21]:
num_df = pd.read_csv("c:/data/num222.csv")
num_df.head()

,사업자번호,결산년월,유동자산,매출채권,비유동자산,유형자산,자산총계,유동부채,비유동부채,부 채 총 계,...,재고자산회전율(회),매출채권회전율(회),매입채무회전율(회),미수금,매출원가,무형자산,재고자산,결산연도,결산월,폐업_유무
0,1018100340,2021-12-31,1175030.0,273522.0,37135811.0,993025.0,38310842.0,9494272.0,4901383.0,14395654.0,...,1.000000e+12,3.497900e+01,1.000000e+12,3243.0,NaN,NaN,NaN,2021,12,0
1,1018100772,2021-12-31,549804.0,NaN,21237198.0,21231948.0,21787002.0,3733712.0,12704550.0,16438262.0,...,1.000000e+12,1.000000e+12,1.000000e+12,517157.0,337407.0,NaN,NaN,2021,12,0
2,1018101126,2021-12-31,1798623.0,115892.0,35555977.0,34136073.0,37354601.0,9435217.0,3258245.0,12693461.0,...,1.000000e+12,2.682400e+01,1.000000e+12,910.0,1506709.0,1.0,NaN,2021,12,0
3,1018101242,2021-12-31,543038.0,114573.0,24420419.0,21795940.0,24963457.0,6684822.0,1956000.0,8640822.0,...,1.000000e+12,1.439400e+01,1.000000e+12,NaN,1103070.0,NaN,NaN,2021,12,0
4,1018103819,2021-12-31,1608654.0,18608.0,11514039.0,11063056.0,13122693.0,6404524.0,1621901.0,8026426.0,...,1.000000e+12,2.099600e+01,1.000000e+12,NaN,NaN,NaN,NaN,2021,12,0

In [15]:
fin_df['결산연도'] = fin_df['datetime'].dt.year
fin_df['결산월'] = fin_df['datetime'].dt.month
fin_df.head()

KeyError: 'datetime'